region: us-east-1

# Updated after ParameterStack
parameter:
  arn:
    parameter_store: xxxxxxxxxxxxxxxx
    secret_store: xxxxxxxxxxxxxxxx

# Used by CognitoStack
cognito:
  function:
    restrict_domain:    
      name: ms1-restrict-domain
  user_pool:  
    name: ms1-users
    region: us-east-1
  app_client:    
    name: ms1-client

# Used by BackendStack
backend:
  service:
    name: ms1-backend
    url: xxxxxxxxxxxxxxxx

# Used by FrontendStack   
frontend:
  bucket:
    name: ms1-bucket-5999
  cognito:
    user_pool:
      id: xxxxxxxxxxxxxxxx     
      region: xxxxxxxxxxxxxxxx
    app_client:
      id: xxxxxxxxxxxxxxxx
  url: xxxxxxxxxxxxxxxx

