region: us-east-1

# Updated after ParameterStack
parameter:
  arn:
    parameter_store: arn:aws:ssm:us-east-1:960674118045:parameter/message/ms-1
    secret_store: arn:aws:secretsmanager:us-east-1:960674118045:secret:secret_message-jqFF9V

# Used by CognitoStack
cognito:
  function:
    restrict_domain:    
      name: ms1-restrict-domain
  user_pool:  
    name: ms1-users
    region: us-east-1
  app_client:    
    name: ms1-client
    
    
# Used by BackendStack
backend:
  service:
    name: ms1-backend
  url: http://localhost:8000

# Used by FrontendStack   
frontend:
  bucket:
    name: ms1-bucket-5999
  cognito:
    user_pool:
      id: us-east-1_XmJegtPm4     
      region: us-east-1
    app_client:
      id: 4cm86jnf64085ki8mfuin9le7g
  url: http://localhost:5173

